# Builds preview-wasm (ym38x6-ui's `preview` feature, wrapped via wasm-bindgen; wasm32-unknown-unknown
# only crate) and splices the generated no-modules glue code plus a base64-embedded copy of the wasm
# binary directly into index.html between the BEGIN/END GENERATED markers. This keeps the tool a
# single self-contained HTML file (no server, no external file references, works via file://) even
# though the XML parsing/codegen/layout AND the preview rendering itself (real egui widgets via
# eframe's WebRunner) now run as wasm instead of hand-written SVG-drawing JS.
#
# Uses cargo/wasm-bindgen under rustup's install (scoop's cargo has no wasm32 target), same setup
# as gesture-app/scripts/build-editor-wasm.ps1. Renamed/rewritten from build-wasm.ps1 (which built
# the older codegen-wasm crate, now superseded by preview-wasm and removed).
# Note: this script is kept ASCII-only for the same reason as build-editor-wasm.ps1 (a spawned
# legacy powershell.exe, not pwsh, may misread BOM-less UTF-8 source using the system codepage).
# All file I/O below uses explicit UTF-8 encoding so the embedded JSDoc comments (which do contain
# Japanese, copied verbatim from panel-codegen's Rust doc comments) survive intact regardless.

$ErrorActionPreference = "Stop"

$rustupCargo = "$env:USERPROFILE\.cargo\bin\cargo.exe"
$wasmBindgen = "$env:USERPROFILE\.cargo\bin\wasm-bindgen.exe"
$crateDir    = Join-Path $PSScriptRoot "..\..\ui\preview-wasm"
$indexHtml   = Join-Path $PSScriptRoot "index.html"
$wasmFile    = Join-Path $crateDir "target\wasm32-unknown-unknown\release\preview_wasm.wasm"
$tmpOutDir   = Join-Path $crateDir "target\wasm-bindgen-out"

if (-not (Test-Path $rustupCargo)) {
    throw "rustup cargo not found: $rustupCargo. Setup: see gesture-app/scripts/build-editor-wasm.ps1 header comment."
}
if (-not (Test-Path $wasmBindgen)) {
    throw "wasm-bindgen-cli not found: $wasmBindgen. Run: cargo install wasm-bindgen-cli --version 0.2.126 --force"
}

& $rustupCargo build --release --target wasm32-unknown-unknown --manifest-path (Join-Path $crateDir "Cargo.toml")
if ($LASTEXITCODE -ne 0) { throw "preview-wasm cargo build failed (exit $LASTEXITCODE)" }

if (Test-Path $tmpOutDir) { Remove-Item $tmpOutDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $tmpOutDir | Out-Null

& $wasmBindgen --target no-modules --out-dir $tmpOutDir --out-name preview_wasm $wasmFile
if ($LASTEXITCODE -ne 0) { throw "wasm-bindgen failed (exit $LASTEXITCODE)" }

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$glueJs = [System.IO.File]::ReadAllText((Join-Path $tmpOutDir "preview_wasm.js"), [System.Text.Encoding]::UTF8)
$wasmBytes = [System.IO.File]::ReadAllBytes((Join-Path $tmpOutDir "preview_wasm_bg.wasm"))
$wasmBase64 = [System.Convert]::ToBase64String($wasmBytes)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("<!-- BEGIN GENERATED: preview-wasm wasm (regenerated by build-preview-wasm.ps1, do not hand-edit) -->")
$lines.Add("<script>")
$lines.Add("/* preview_wasm.js (wasm-bindgen --target no-modules output, embedded verbatim) */")
$lines.Add($glueJs)
$lines.Add("</script>")
$lines.Add("<script>")
$lines.Add('const PREVIEW_WASM_BASE64 = "' + $wasmBase64 + '";')
$lines.Add("(function(){")
$lines.Add("  function base64ToBytes(b64) {")
$lines.Add("    const bin = atob(b64);")
$lines.Add("    const bytes = new Uint8Array(bin.length);")
$lines.Add("    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);")
$lines.Add("    return bytes;")
$lines.Add("  }")
$lines.Add("  wasm_bindgen.initSync(base64ToBytes(PREVIEW_WASM_BASE64));")
$lines.Add("})();")
$lines.Add("</script>")
$lines.Add("<!-- END GENERATED: preview-wasm wasm -->")
$generatedBlock = [string]::Join("`n", $lines)

$beginMarker = "<!-- BEGIN GENERATED: preview-wasm wasm (regenerated by build-preview-wasm.ps1, do not hand-edit) -->"
$endMarker = "<!-- END GENERATED: preview-wasm wasm -->"
$htmlText = [System.IO.File]::ReadAllText($indexHtml, [System.Text.Encoding]::UTF8)
$beginIdx = $htmlText.IndexOf($beginMarker)
$endIdx = $htmlText.IndexOf($endMarker)
if ($beginIdx -lt 0 -or $endIdx -lt 0) {
    throw "index.html is missing the BEGIN/END GENERATED markers. See build-preview-wasm.ps1."
}
$endIdx += $endMarker.Length
$newHtml = $htmlText.Substring(0, $beginIdx) + $generatedBlock + $htmlText.Substring($endIdx)
[System.IO.File]::WriteAllText($indexHtml, $newHtml, $utf8NoBom)

Remove-Item $tmpOutDir -Recurse -Force

Write-Host "preview-wasm built and embedded -> $indexHtml"
