[package]
name = "vgm2op505"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vgm2op505"
path = "src/main.rs"

[dependencies]
vgm2x6 = { path = "../../../ym38x6/tools/vgm2x6" }
opm2op505 = { path = "../opm2op505" }
mucom2op505 = { path = "../mucom2op505" }
opm2x6 = { path = "../../../ym38x6/tools/opm2x6" }
mucom2x6 = { path = "../../../ym38x6/tools/mucom2x6" }
op505-core = { path = "../../core" }
ym38x6-core = { path = "../../../ym38x6/core" }
sound-core = { path = "../../../sound/core" }
